;;; devcontainer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from devcontainer.el

(autoload 'devcontainer-up "devcontainer"
"Start the devcontainer of the current project.

If SHOW-BUFFER is non nil, the buffer of the startup process is shown.

(fn &optional SHOW-BUFFER)" t)
(autoload 'devcontainer-execute-command "devcontainer"
"Execute COMMAND in the container – batch mode.

(fn COMMAND)" t)
(autoload 'devcontainer-execute-command-interactive "devcontainer"
"Execute COMMAND in the container – interactive mode.

(fn COMMAND)" t)
(autoload 'devcontainer-restart "devcontainer"
"Restart the devcontainer of the current project.

If SHOW-BUFFER is non nil, the buffer of the startup process is shown.

The primary docker is killed before restart.  Ohter containers of the
devcontainer stack simply remain alive.

(fn &optional SHOW-BUFFER)" t)
(autoload 'devcontainer-rebuild-and-restart "devcontainer"
"Restart the devcontainer of the current project.

If SHOW-BUFFER is non nil, the buffer of the startup process is shown.

The primary docker container is killed and removed before restart.
Moreover the image of the primary docker container is removed to make
sure that the image is rebuilt before the restart.

The primary docker container is killed before restart.  Ohter containers
of the devcontainer stack simply remain alive.

(fn &optional SHOW-BUFFER)" t)
(autoload 'devcontainer-kill-container "devcontainer"
"Kill the primary docker container of the current project." t)
(autoload 'devcontainer-remove-container "devcontainer"
"Remove the primnary docker container of the current project." t)
(autoload 'devcontainer-remove-image "devcontainer"
"Remove the image of the primary docker container of the current project." t)
(defvar devcontainer-mode nil
"Non-nil if Devcontainer mode is enabled.
See the `devcontainer-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `devcontainer-mode'.")
(custom-autoload 'devcontainer-mode "devcontainer" nil)
(autoload 'devcontainer-mode "devcontainer"
"Toggle `devcontainer-mode'.

When `devcontainer-mode' is active and the current projects is defining
a devcontainer, all compilation launches are prepended with
`devcontainer exec' so that the compilation is performed inside the
devcontainer.  Use `devcontainer-execute-outside-container' to exclude
programs from being executed inside the devcontainer.

This is a global minor mode.  If called interactively, toggle the
`Devcontainer mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='devcontainer-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'devcontainer-tramp-dired "devcontainer"
"Open a Dired window inside devcontainer's working folder.

When called interactively, all the arguments are determined
automatically.  The arguments for the non-interactive call are set up in
a compatible way to `devcontainer-post-startup-hook'.

* CONTAINER-ID – a string representing the container id
* CONTAINER-NAME – a string representing the container-name
* REMOTE-USER – a string of the remote user name
* REMOTE-WORKDIR – the workdir path in the container.

(fn CONTAINER-ID CONTAINER-NAME REMOTE-USER REMOTE-WORKDIR)" t)
(register-definition-prefixes "devcontainer" '("devcontainer-"))

;;; End of scraped data

(provide 'devcontainer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; devcontainer-autoloads.el ends here
